spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: ksriman17

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  # JPA Settings
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Update to MySQL8Dialect for MySQL 8.x or use MySQL57Dialect for MySQL 5.x
